// Grammar-compressed genus sequence of the runs of a tag array (optional second level of compression; tag.hpp).
// The run-length tag array stores the genus of each run; here those genera are instead generated by a RePair grammar
// (built with bigrepair -i), encoded as in Gagie et al., "Practical random access to SLP-compressed texts" (SPIRE 2020):
// symbols are grouped by expansion length (in runs) and named by (length, offset in their group), so expansion lengths
// come for free.  Within the group of length l, the rules are sorted by the length of their left child, and each
// sub-group (l, left length) stores, for each rule, its children's offsets in fixed widths.  Terminals form the group of
// length 1, with offset = genus.  The top-level sequence C is stored as the cumulative run counts of its symbols (an
// Elias-Fano bitvector over the runs) plus their offsets.
#pragma once
#include <sdsl/sd_vector.hpp>
#include <sdsl/int_vector.hpp>
#include <vector>
#include <algorithm>
#include <cstdint>
#include <fstream>

namespace rz {

struct gram_tags {
    uint64_t rho = 0;                         // number of runs (= expansion length of the whole grammar)
    uint32_t maxlen = 0;
    std::vector<uint32_t> grp;                // expansion length -> group id (0 = terminals; UINT32_MAX = no group)
    std::vector<uint32_t> gfirst;             // group -> first sub-group (gfirst[ngroups] = number of sub-groups)
    struct Sub { uint32_t start, left; uint64_t bit; uint8_t wl, wr; };
    std::vector<Sub> subs;                    // sorted by (group, start)
    std::vector<uint64_t> bits;               // children's offsets, packed
    sdsl::sd_vector<> CB; sdsl::rank_support_sd<> CBr; sdsl::select_support_sd<> CBs;   // starts of C's symbols, in runs
    sdsl::int_vector<> Coff;                  // offsets of C's symbols in their groups
    static inline thread_local std::vector<std::pair<uint32_t, uint32_t>> stk;         // (length, offset), per thread

    static inline uint64_t getbits(const std::vector<uint64_t> &w, uint64_t pos, unsigned width) {
        if (width == 0) return 0;
        uint64_t i = pos >> 6, o = pos & 63, v = w[i] >> o;
        if (o + width > 64) v |= w[i + 1] << (64 - o);
        return width == 64 ? v : v & ((1ULL << width) - 1);
    }
    // children of the symbol (l >= 2, o): (left length, left offset, right offset)
    inline void children(uint32_t l, uint32_t o, uint32_t &ll, uint32_t &lo, uint32_t &ro) const {
        uint32_t g = grp[l], a = gfirst[g], b = gfirst[g + 1];
        while (b - a > 1) { uint32_t m = (a + b) / 2; if (subs[m].start <= o) a = m; else b = m; }   // last sub with start <= o
        const Sub &s = subs[a]; uint64_t p = s.bit + (uint64_t)(o - s.start) * (s.wl + s.wr);
        ll = s.left; lo = (uint32_t)getbits(bits, p, s.wl); ro = (uint32_t)getbits(bits, p + s.wl, s.wr);
    }
    // calls f(genus) for runs a, a+1, ..., a+cnt-1 (cnt >= 1)
    template <class F> inline void decode(uint64_t a, uint64_t cnt, F f) const {
        uint64_t k = CBr(a + 1) - 1, st = CBs(k + 1), off = a - st;
        uint64_t nsym = Coff.size();
        uint32_t l = (uint32_t)((k + 1 < nsym ? CBs(k + 2) : rho) - st), o = (uint32_t)Coff[k];
        auto &S = stk; S.clear();
        uint32_t ll, lo, ro;
        while (l > 1) { children(l, o, ll, lo, ro); if (off < ll) { S.push_back({l - ll, ro}); l = ll; o = lo; } else { off -= ll; l -= ll; o = ro; } }
        f(o);
        while (--cnt) {
            if (S.empty()) { ++k; st = CBs(k + 1); l = (uint32_t)((k + 1 < nsym ? CBs(k + 2) : rho) - st); o = (uint32_t)Coff[k]; }
            else { l = S.back().first; o = S.back().second; S.pop_back(); }
            while (l > 1) { children(l, o, ll, lo, ro); S.push_back({l - ll, ro}); l = ll; o = lo; }
            f(o);
        }
    }
    uint64_t bytes() const {
        return grp.size() * 4 + gfirst.size() * 4 + subs.size() * sizeof(Sub) + bits.size() * 8
               + sdsl::size_in_bytes(CB) + sdsl::size_in_bytes(CBr) + sdsl::size_in_bytes(CBs) + sdsl::size_in_bytes(Coff);
    }
    template <class V> static void wvec(std::ostream &o, const std::vector<V> &v) { uint64_t m = v.size(); o.write((char *)&m, 8); o.write((char *)v.data(), m * sizeof(V)); }
    template <class V> static void rvec(std::istream &i, std::vector<V> &v) { uint64_t m; i.read((char *)&m, 8); v.resize(m); i.read((char *)v.data(), m * sizeof(V)); }
    void serialize(std::ostream &o) const {
        o.write((char *)&rho, 8); o.write((char *)&maxlen, 4); wvec(o, grp); wvec(o, gfirst); wvec(o, subs); wvec(o, bits);
        CB.serialize(o); CBr.serialize(o); CBs.serialize(o); Coff.serialize(o);
    }
    void load(std::istream &i) {
        i.read((char *)&rho, 8); i.read((char *)&maxlen, 4); rvec(i, grp); rvec(i, gfirst); rvec(i, subs); rvec(i, bits);
        CB.load(i); CBr.load(i, &CB); CBs.load(i, &CB); Coff.load(i);
    }

    // build from bigrepair -i output (prefix.R: alphabet size, then rule pairs; prefix.C: top-level sequence)
    bool build(const std::string &prefix, std::string &err) {
        std::ifstream fr(prefix + ".R", std::ios::binary); if (!fr) { err = "cannot read " + prefix + ".R"; return false; }
        fr.seekg(0, std::ios::end); uint64_t sz = fr.tellg(); fr.seekg(0);
        int32_t alpha; fr.read((char *)&alpha, 4); uint64_t R = (sz - 4) / 8;
        std::vector<int32_t> rl(2 * R); fr.read((char *)rl.data(), 8 * R);
        uint64_t S = alpha + R; std::vector<uint32_t> len(S, 1);
        maxlen = 1;
        for (uint64_t i = 0; i < R; ++i) { len[alpha + i] = len[rl[2 * i]] + len[rl[2 * i + 1]]; maxlen = std::max(maxlen, len[alpha + i]); }
        // groups: id 0 = length 1 (terminals), then lengths >= 2 in increasing order
        std::vector<uint64_t> gsz(maxlen + 1, 0); for (uint64_t i = 0; i < R; ++i) gsz[len[alpha + i]]++;
        grp.assign(maxlen + 1, UINT32_MAX); grp[1] = 0; uint32_t ng = 1;
        for (uint32_t l = 2; l <= maxlen; ++l) if (gsz[l]) grp[l] = ng++;
        gsz[1] = alpha;
        auto width = [&](uint32_t l) { uint64_t s = gsz[l]; unsigned b = 0; while ((1ULL << b) < s) ++b; return (uint8_t)b; };
        // order rules by (length, left length); offset of a rule = its rank in its group
        std::vector<uint32_t> ord(R); for (uint64_t i = 0; i < R; ++i) ord[i] = (uint32_t)i;
        std::sort(ord.begin(), ord.end(), [&](uint32_t x, uint32_t y) {
            uint32_t lx = len[alpha + x], ly = len[alpha + y];
            if (lx != ly) return lx < ly;
            uint32_t ax = len[rl[2 * x]], ay = len[rl[2 * y]];
            return ax != ay ? ax < ay : x < y; });
        std::vector<uint32_t> off(S);
        for (int32_t t = 0; t < alpha; ++t) off[t] = t;
        { uint64_t i = 0; while (i < R) { uint32_t l = len[alpha + ord[i]]; uint64_t j = i; while (j < R && len[alpha + ord[j]] == l) { off[alpha + ord[j]] = (uint32_t)(j - i); ++j; } i = j; } }
        // sub-groups and packed children's offsets
        subs.clear(); gfirst.assign(ng + 1, 0); bits.clear(); uint64_t pos = 0;
        gfirst[0] = 0; subs.push_back({0, 0, 0, 0, 0});   // group 0 (terminals) has a dummy sub-group, never used
        uint64_t i = 0; uint32_t gcur = 0;
        std::vector<uint64_t> tmp; tmp.reserve(1);
        auto put = [&](uint64_t v, unsigned w) {
            if (w == 0) return;
            uint64_t idx = pos >> 6, o = pos & 63; if (bits.size() <= idx + 1) bits.resize(idx + 2, 0);
            bits[idx] |= v << o; if (o + w > 64) bits[idx + 1] |= v >> (64 - o);
            pos += w;
        };
        while (i < R) {
            uint32_t r0 = ord[i], l = len[alpha + r0], ll = len[rl[2 * r0]], g = grp[l];
            while (gcur < g) gfirst[++gcur] = (uint32_t)subs.size();
            Sub s{(uint32_t)off[alpha + r0], ll, pos, width(ll), width(l - ll)};
            subs.push_back(s);
            uint64_t j = i;
            while (j < R && len[alpha + ord[j]] == l && len[rl[2 * ord[j]]] == ll) {
                uint32_t r = ord[j]; put(off[rl[2 * r]], s.wl); put(off[rl[2 * r + 1]], s.wr); ++j;
            }
            i = j;
        }
        while (gcur < ng) gfirst[++gcur] = (uint32_t)subs.size();
        bits.resize(pos / 64 + 2); bits.shrink_to_fit();
        // top-level sequence
        std::ifstream fc(prefix + ".C", std::ios::binary); if (!fc) { err = "cannot read " + prefix + ".C"; return false; }
        fc.seekg(0, std::ios::end); uint64_t nc = (uint64_t)fc.tellg() / 4; fc.seekg(0);
        std::vector<int32_t> C(nc); fc.read((char *)C.data(), 4 * nc);
        rho = 0; for (int32_t x : C) rho += len[x];
        { sdsl::sd_vector_builder b(rho, nc); uint64_t p = 0; for (int32_t x : C) { b.set(p); p += len[x]; } CB = sdsl::sd_vector<>(b); }
        sdsl::util::init_support(CBr, &CB); sdsl::util::init_support(CBs, &CB);
        uint32_t mo = 0; for (int32_t x : C) mo = std::max(mo, off[x]);
        Coff = sdsl::int_vector<>(nc, 0, std::max(1, (int)sdsl::bits::hi(mo) + 1)); for (uint64_t t = 0; t < nc; ++t) Coff[t] = off[C[t]];
        return true;
    }
};

}  // namespace rz
