// Builds a grammar-compressed tag array (tag.hpp + gtag.hpp): the run starts of an unsampled tag array, with the genera
// of its runs generated by a RePair grammar (bigrepair -i on the runs' genus sequence, e.g. from tools/grammar/tokwrite).
// usage: rz-gtagbuild bac.s1.tag grammar_prefix out.gtag
//   checks that the grammar generates exactly the genera of the runs, then writes out.gtag (rz-classify -T, RZ_COUNTS=1).
#include "tag.hpp"
#include <chrono>
using namespace rz;
int main(int argc, char **argv) {
    if (argc != 4) { fprintf(stderr, "usage: rz-gtagbuild bac.s1.tag grammar_prefix out.gtag\n"); return 1; }
    double t0 = now();
    tag_index X; if (!X.load(argv[1], false) || X.gram) { fprintf(stderr, "cannot load the run-length tag array %s\n", argv[1]); return 1; }
    if (X.s != 1) { fprintf(stderr, "the tag array must be unsampled (s = 1)\n"); return 1; }
    auto G = std::make_shared<gram_tags>(); std::string err;
    if (!G->build(argv[2], err)) { fprintf(stderr, "%s\n", err.c_str()); return 1; }
    if (G->rho != X.rho) { fprintf(stderr, "the grammar generates %lu runs, the tag array has %lu\n", G->rho, X.rho); return 1; }
    uint64_t i = 0, bad = 0;
    G->decode(0, X.rho, [&](uint32_t g) { if (g != X.L[i]) ++bad; ++i; });
    if (bad) { fprintf(stderr, "ERROR: %lu runs get the wrong genus\n", bad); return 1; }
    uint64_t starts = sdsl::size_in_bytes(X.RB) + sdsl::size_in_bytes(X.RBr) + sdsl::size_in_bytes(X.RBs), Lb = sdsl::size_in_bytes(X.L);
    X.gram = G; X.L = sdsl::int_vector<>(0);
    X.save_gram(argv[3]);
    uint64_t sub = G->subs.size() * sizeof(gram_tags::Sub), bits = G->bits.size() * 8,
             cb = sdsl::size_in_bytes(G->CB) + sdsl::size_in_bytes(G->CBr) + sdsl::size_in_bytes(G->CBs) + sdsl::size_in_bytes(G->Coff);
    fprintf(stderr, "runs %lu checked | bytes %lu: run starts %lu, grammar %lu (children's offsets %lu, sub-groups %zu = %lu, "
            "groups %lu, C %zu symbols = %lu) | genera in the run-length tag array were %lu bytes | %.0f s\n",
            X.rho, starts + G->bytes(), starts, G->bytes(), bits, G->subs.size(), sub, (G->grp.size() + G->gfirst.size()) * 4,
            G->Coff.size(), cb, Lb, now() - t0);
    return 0;
}
