#!/bin/sh
# g++ with two fixes for old code under GCC 15: headers that forget <cstdint>, and
# sdsl-lite template bodies that no longer compile but are never used.
exec g++ -include cstdint -Wno-template-body "$@"
